### ISSUE TITLE
Detected as bot -> low quality answers

### ISSUE THREAD

**Issue by holymode** [acheong08/ChatGPT#220]
Does this lib also get detected as bot user? Someone on PyChatGPT repo suspected that OpenAI introduced bot detection. The answers were usually short and low quality. I just tested a bit and it seems to be the issue here as well. 

On chrome you always get long answers, but with this lib the answers are also on the shorter side even if you retry the same prompt. 

You might want to check it out. 

[Issue on PyChatGPT repo, he fixed it already.](https://github.com/rawandahmad698/PyChatGPT/issues/78)

**Comment by rawandahmad698** [comment]
I have a bypass, don't worry, whoever reading, We're unblockable, and unbannable (If those are words)...

Update soon

**Comment by transitive-bullshit** [comment]
I'm not able to discern any noticeable difference in result quality between the web version (using a fresh account) and the API version. This is using https://github.com/transitive-bullshit/chatgpt-api and it's accompanying [twitter bot](https://github.com/transitive-bullshit/chatgpt-twitter-bot).

The bot is cycling through ~20 different accounts, though, so maybe that's helped to prevent bot detection?

This may also be due to OpenAI just generally tweaking things while having trouble scaling their servers. I saw this for the first time today on a Google OAuth-based account:

<img width="815" alt="CleanShot 2022-12-10 at 16 54 54@2x" src="https://user-images.githubusercontent.com/552829/206880572-1d985f7f-51ab-4891-8846-4bb350aa0886.png">

**Comment by acheong08** [comment]
@transitive-bullshit I don't think there is an actual difference. It's just that the system gives out lower quality answers sometimes. It happens on the web occasionally as well.

**Comment by transitive-bullshit** [comment]
Agreed

**Comment by acheong08** [comment]
There should be literally no difference. It uses the exact same API.

**Comment by acheong08** [comment]
I see the API issue. I fixed it in the latest commit. Will publish once tested

**Comment by acheong08** [comment]
@holymode Fixed in https://github.com/acheong08/ChatGPT/releases/tag/0.0.36

**Comment by rawandahmad698** [comment]
@transitive-bullshit @acheong08 next to variant won't fix this. As already stated. The responses via every bot is different to the browser, unless you're using a Chromium/Controlled browser.

**Comment by acheong08** [comment]
Changing it to variant changes the responses for me.

**Comment by acheong08** [comment]
What do you propose @rawandahmad698

**Comment by acheong08** [comment]
Unless this is fingerprinting related, I see no differences with the website's requests and responses

**Comment by transitive-bullshit** [comment]
What do you suppose `action: 'next'` vs action: 'variant'` actually does differently?

I'm guessing we'd all like to keep our respective API interfaces as close to the eventual public / official API as possible, so having a better understanding here couldn't hurt.

@rawandahmad698 would also love to understand what you're proposing and where the problem may lie.

Also, thanks to both of you guys for your excellent work on these projects this past week. Hacking w/ ChatGPT has been a ton of fun and I've learned a lot checking out your codebases. 🙏

**Comment by rawandahmad698** [comment]
lol u guys so impatient it's 5 am here. As promised a full update with explanation on my repo very soon haha

**Comment by acheong08** [comment]
> What do you suppose action: 'next' vs action: 'variant' actually does differently?

There does seem to be some effect on the output although its significance is subjective.

> would also love to understand what you're proposing and where the problem may lie.

Reading through the code there: https://github.com/rawandahmad698/PyChatGPT/blob/955883864e35d9aadcfd9c1ba9f6f4e7ae845672/src/pychatgpt/classes/chat.py#L46-L72

I don't see any major changes. He might not have published the update yet

**Comment by transitive-bullshit** [comment]
Investigating the API once more, I honestly don't think `action: 'variant'` does what you want. Initial responses are always generated via `action: 'next'` and it's only when you ask it to retry, that `action: 'variant'` is used — which is probably meant as a special case only in the event that the same `message.id`, `parent_message_id`, and `conversation_id` need to be re-generated. This isn't supported in my API wrapper at the moment, for instance, because we're generating a random `message.id` every time, but that's a completely separate feature from the core conversation response feature.

In any case, I still don't see this as an actual issue, and I don't believe that there's anything worth changing here until there's something more conclusive to the contrary.

**Comment by rawandahmad698** [comment]
@transitive-bullshit wait. Preparing the update

**Comment by transitive-bullshit** [comment]
@rawandahmad698 ok ok haha 😂 hope you got some good sleep :)

**Comment by rawandahmad698** [comment]
Power went out. Give me an hour or so 💀
