### ISSUE TITLE
[BUG] MacOS bug but in Ubuntu

### ISSUE THREAD

**Issue by GSstarGamer** [acheong08/ChatGPT#391]
**Describe the bug**
MacOS bug but in my ubuntu OS. Im not sure why but I still get 
`UnboundLocalError: local variable 'driver' referenced before assignment`

**Expected behavior**
MacOS bug

**Comment by GSstarGamer** [comment]
Yes I have done everything told in that MacOS bug, still not working (My config is in code)

**Comment by acheong08** [comment]
Can you show the full stack trace?

**Comment by acheong08** [comment]
> UnboundLocalError: local variable 'driver' referenced before assignment

It means that `uc.Chrome(...)` failed. What is your `pip3 show undetected_chromedriver`

**Comment by winddack** [comment]
I have the same problem。
Name: undetected-chromedriver
Version: 3.2.1
Summary: ('Selenium.webdriver.Chrome replacement with compatiblity for Brave, and other Chromium based browsers.', 'Not triggered by CloudFlare/Imperva/hCaptcha and such.', 'NOTE: results may vary due to many factors. No guarantees are given, except for ongoing efforts in understanding detection algorithms.')
Home-page: https://github.com/ultrafunkamsterdam/undetected-chromedriver
Author: UltrafunkAmsterdam
Author-email: info@blackhat-security.nl
License: GPL-3.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: requests, selenium, websockets
Required-by: pyChatGPT, revChatGPT

**Comment by acheong08** [comment]
Full stack trace please. This is an expected error when Chrome fails to start

**Comment by acheong08** [comment]
Please head over to https://github.com/acheong08/ChatGPT/issues/381. This is probably a duplicate. Report your errors there
