### ISSUE TITLE
How is this legal?

### ISSUE THREAD

**Issue by ghost** [acheong08/ChatGPT#394]
Add a note in README, explaining how this is legal\moral to abuse chatGPT service.

I'd like to see a clear explanation from both the @acheong08 and @github why this (and other modules like it) are not being taken down for violating [OpenAI ToS](https://openai.com/terms/)?

![Screenshot_20221230_211907](https://user-images.githubusercontent.com/80627726/210109040-a6a5eb53-8f61-421e-8b61-3e7230ebacb7.png)

**Comment by Disa-Kizonda** [comment]
🤓

**Comment by acheong08** [comment]
Breaking the terms of service is not illegal. OpenAI does not make laws. 

(They can ban your account if known but that is unlikely due to the effort it takes to detect such violations)

**Comment by BlitzJB** [comment]
I missed the part where its my problem

**Comment by wwwmaster1** [comment]
This is a discussion worth having. As the most media-covered and talked about AI innovation in years, it can be argued that this package is not only legal and ethical, but even necessary to assure democratic access to the technology in ways that OpenAI is (currently) neglecting.

Primarily, by limiting use to only a web console, the technology may not be accessible to those that rely on non-standard, private or experimental assistive technologies. Which would appear to be against the inclusive ethos of the company.

OpenAi gives the impression that it is their desire not to own the entirety of the LLM universe, nor stifle innovation,but to assure that this technology progresses safely and to the benefit of humankind. 

Surely as a for profit company (no longer a nonprofit) it needs to preemptively establish certain defenses in the EULA/TOS, but it is at the company's discretion whether or not to act on violations of the stated terms.

Further, not that use is an admission of breach, but it is generally not illegal to breach a contract,even if such non-negotiable terms are considered a contract. [IANAL/TINLA]

Lastly, it may even be the will of the company that safe experimentation be possible through these unsanctioned methods, as it may add any form of validation, albeit at the cost of inclusion.

-Igor Ilyinsky, ListenUp DAO

**Comment by DiamondDemon669** [comment]
Technically, this project uncoveres the secret ChatGPT API, not the source code of their models. its not against their terms of service

**Comment by pepi99** [comment]
Who were you? @UCWV6N8pcAL6bjiWMZtZrKrQwT UCWV6N8pcAL6bjiWMZtZrKrQwT]

**Comment by acheong08** [comment]
This user does have a valid concern: Microsoft owns GitHub and is a shareholder in OpenAI. They can therefore take this repository down if they feel like it. This was already experienced when @AUTOMATIC1111 was suspended for a day

**Comment by hahyes** [comment]
Just read, what is below in iv).

**Comment by acheong08** [comment]
Yes. I acknowledge I am breaking OpenAI TOS. TOS is not law though

**Comment by nibblebits** [comment]
Breaking TOS can lead to a lawsuit just bare in mind. If someone makes a great product using this package they are screwed when OPENAI file a lawsuit against them and bankrupt their new venture. Just pay for the API.. The problem with this package is the API can be changed at any time and screw it.

**Comment by acheong08** [comment]
> Breaking TOS can lead to a lawsuit just bare in mind. If someone makes a great product using this package they are screwed when OPENAI file a lawsuit against them and bankrupt their new venture. Just pay for the API.. The problem with this package is the API can be changed at any time and screw it.

If you're breaking TOS to make a commercial product, yes. It should be fine for personal projects

**Comment by acheong08** [comment]
> Just pay for the API.. 

API not released yet. I will archive this once it is

**Comment by acheong08** [comment]
>  The problem with this package is the API can be changed at any time and screw it.

That is true. OpenAI has done that many times already

**Comment by nibblebits** [comment]
Even for personal projects your still liable for breach of license. Lets say you make a cool tool that lets someone use ChatGPT on their windows computer like a task bar search type of thing but talks with ChatGPT. If OPENAI had plans to make such a product they could sue for the breach of that terms and conditions clause regardless if you released it for free or not.

As for yourself you could be liable should someone use your library and make money, as you broke the terms and conditions to make this product that then someone might go onto abuse. Its important to know your standing so you dont get into trouble

**Comment by acheong08** [comment]
I'm in a country where copyright law doesn't exactly exist. Even if I am legally liable, they can't reach me here.

**Comment by acheong08** [comment]
And I am not actually violating their copyright. Their API is public and authenticated. it still requires an OpenAI account

**Comment by nibblebits** [comment]
I didnt say copyright, I said that your in violation of the terms of service, which is a contract you signed when you signed up to the service. I'm just making you aware because I don't want to see you get sued for this as if successful products from from your plugin of course they will prosecute someone and it could be you for breach of contract.

**Comment by acheong08** [comment]
>  violation of the terms of service, which is a contract you signed when you signed up to the service.

Those who use this library violate the TOS which I am not liable for. That is part of my License agreement.

**Comment by acheong08** [comment]
I personally don't use my own library much

**Comment by nibblebits** [comment]
The TOS states about reverse enginnering which you did. Don;'t worry I am not trying to argue with you just trying to save you from a problem later on. It is up to you I have told you the law I know the law very well as I am in lawsuits frequently due to copyright infringment. I sue people a lot so I have understanding of this area. Though I am not a solicitor or a lawyer but I understand basic infringment laws and breach of contract laws.

All the best

**Comment by acheong08** [comment]
> I have understanding of this area. 

So what is your recommendation?

**Comment by nibblebits** [comment]
Honestly, to take this repository down. Your terms of service means nothing, all that prevents is someone using your library trying to sue you for damages later on. It does not prevent ChatGPT sueing you for the reverse enginnering that you did that lead to Product X being created which cost them millions. Product X being a product someone made with your library.

But if you think your country is corrupt and you can get away with it then go for it I guess. However if your in a developed country like USA, UK or european union then this is a problem. Even worse if your in the EU as theirs a european court allowing any legal entity in a european country to sue another legal entity in another european country and the process is generally easier than having to sue someone in their home countries court. Though I have never sued through european court so I cant speak from experience just what I have read. I've sued through UK courts mainly.

**Comment by nibblebits** [comment]
But from a realistic point of view if Product X does really well it makes sense from a business point of view to sue Product X. 
I have a personal example of where I have sued someone for someone elses actions. I am sueing a web hosting company for something their customer did. Their customer had a website infringing my copyright. However he was unreachable. I told the hosting company remove the files hes infringing my copyright. They ignored me for months. Under UK law they then became liable for the infringment. I am now sueing them for 5k

**Comment by acheong08** [comment]
A hosting provider is liable for what they host. However, I am not hosting anything. Basic TOS infringement is not illegal: https://www.findlaw.com/legalblogs/ninth-circuit/violation-of-a-websites-terms-of-service-is-not-criminal/

It isn't "hacking" as the access is authorized via a token

**Comment by acheong08** [comment]
And according to https://opensource.org/licenses, open source code cannot be held liable for the actions of users

**Comment by acheong08** [comment]
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

**Comment by nibblebits** [comment]
I never said that it was criminal. Theirs cival and criminal proceedings. Criminal lands you in jail. Cival proceedings are for monies damages.

Breach of TOS is enforceable in court at least in UK and many other developed countries. When you press "Agree" you are agreeing to those it becomes a digital contract.

Lets say Product X made 1 million dollars and they sue you for those damages as your breach of contract is what lead to that outcome . They go to court and prove you signed those TOS and then proved you made the library that Product X used then you are in a lot of trouble.

Yes it may not be criminal proceedings but it can be cival which can recover lost monies through action.

The license snippet you provided I am assuming is what you have issued here for this repository. This prevents anyone using your library from sueing you if something bad happens like they are sued for using it. It does not prevent ChatGPT from losing the right to sue you for damages since your in violation of their TOS.

You could also ask CHATGPT these questions it will likely give the same answers im giving you though I have found it to be wrong at times.

**Comment by nibblebits** [comment]
Though from a realistic point of view your an individual lets imagine your poor I don't know your wealth, they likely will leave you alone as the cost will not outweigh the benefit. However be prepared for a letter asking you to remove this repository and if you get one you should do it right away

**Comment by nibblebits** [comment]
Though the clause he referenced above in the screenshot their could be several ways to fight that clause for example it mentions applicable by law. Therefore in the country ChatGPT is registered you could check the local laws to see if the laws allow for reverse enginnering in which case the TOS would be invalid. Law is fun its my second favourite subject other than programming.

But this is how you can be smart and protect yourself, though its best to not go down the rabbit hole to begin with

**Comment by acheong08** [comment]
Should they not be suing the one who broke the TOS? I'm not well versed in the law but there must be a clause where unrelated third parties can't be held liable for someone else breaking the law.

If that was not the case, doesn't that mean OpenAI can sue the provider of their laptop, their ISP, and anyone else even remotely related for this?

**Comment by acheong08** [comment]
> you could check the local laws

Local laws says that western laws are not to be respected. China lol

**Comment by nibblebits** [comment]
Well if you remember when you got your laptop you signed the no-warrenty terms and conditions when you registered your microsoft account. Similar to the one you provided to me just now.

I am not a lawyer like I said and I could be wrong on things but I have a decent understanding of basic law in this regard as I have manged to successfully win 4 claims on my own so far for copyright infringment claims.

Of course for the true legal advice seek a lawyer everything I am saying is just from a prespective of someone who is fasinated by the law and I like a good legal challenge like I do a programming one.

Back to the laptop it is a good argument but I suppose it would be ruled out because the design of a laptop is to do administrative tasks and for entertainment where your library has been created soley for one purpose to exploit the private api so the intent is there you get me.

**Comment by nibblebits** [comment]
Also your the one who agreed to the TOS of that website, since the laptop company didnt agree to any such clauses that would also be another reason they couldnt be prosecuted for this

**Comment by acheong08** [comment]
Based on past cases (https://www.eff.org/deeplinks/2010/07/court-violating-terms-service-not-crime-bypassing) it seems that they will sue you if you provide the service yourself. In this case, @PawanOsman can be sued as he is hosting an endpoint himself and [tonyb](https://justbrowse.io/) can also be sued as he's actually charging for the use of his API based on ChatGPT. However, I just provide source code and don't run anything myself. The user is running it locally

**Comment by acheong08** [comment]
> Also your the one who agreed to the TOS of that website, since the laptop company didnt agree to any such clauses that would also be another reason they couldnt be prosecuted for this

I am not. If you check the setup, it is clear that I have nothing to do with account creation and usage

**Comment by acheong08** [comment]
By signing up, users agree to the TOS. I am not the one signing up for the service and therefore I never agreed to it.

**Comment by nibblebits** [comment]
You had to agree to the TOS to have access to the platform to be able to reverse enginner it in the first place that is the argument they would use

**Comment by nibblebits** [comment]
I tell you what im going to ask chatgpt i am curious what it thinks brb in 5 min

**Comment by acheong08** [comment]
> You had to agree to the TOS to have access to the platform to be able to reverse enginner it in the first place that is the argument they would use

Yes but I am not the one breaking TOS. TOS applies to each user individually. Just because I agreed to TOS does not mean I am liable for every TOS violation by other users

**Comment by nibblebits** [comment]
There is a person who made a ChatGPT library that uses the private API. I believe they are in breach of TOS because the TOS clause states: "Restrictions you may not reverse assemble, reverse compile, decompile, translate or otherwise attempt to discover the source code
or undderlying components of the models, algorithms, and systems of the services (except to the extent such restrictions are contrary to applicable law)"


**A.I response**
The library they used if someone else uses the library and creates a project that makes a lot of money can ChatGPT sue the original person who made the library for damages even though they did not make the project that made a lot of money

It is possible that using the ChatGPT library that utilizes the private API in violation of the terms of service could lead to legal action by OpenAI. However, whether or not OpenAI would choose to pursue such action and whether or not they would be successful would depend on the specific circumstances and whether or not the use of the library resulted in any actual damages to OpenAI. It's worth noting that the use of the library by someone else to create a project that makes a lot of money does not directly affect the liability of the person who created the library, but it's possible that OpenAI will consider the financial gain made by the third party in determining the damages resulting from the TOS violation.

**Comment by nibblebits** [comment]
Yes so its basically what I said. But ChatGPT also gets it wrong. But in short your liable but they would likely sue the person who made Project X though they could come after you

**Comment by acheong08** [comment]
>  does not directly affect the liability of the person who created the library

I am not liable

> but it's possible that OpenAI will consider the financial gain made by the third party in determining the damages resulting from the TOS violation.

The damages will therefore be put on the user of this library

**Comment by acheong08** [comment]
And good luck for them suing someone in China

**Comment by nibblebits** [comment]
Okay, I tried to explain it to you the best I could have a good night mate interesting chat all the best and keep coding

**Comment by nibblebits** [comment]
You misunderstood what it said I have clarified it further below
Can you explain this bit more "does not directly affect the liability of the person who created the library"

A.I Response

When someone creates a library that is used in violation of a terms of service, it does not necessarily mean that they themselves are directly responsible for the violation. Liability for a violation of terms of service typically falls on the person or entity that actually uses the service in a prohibited way. However, the person who created the library may still be held liable if they played a role in facilitating the violation, such as by advertising or promoting the library's use in a way that encourages violation of the terms of service.

In the case of the library you described, if it is using the private API of OpenAI and is in violation of the terms of service, the person who created the library could be held liable for the violation. However, if a third party uses the library and makes a lot of money, the financial gain made by the third party would not directly affect the liability of the person who created the library but it could be considered as a factor by OpenAI in determining the damages resulting from the TOS violation.

Goodnight buddy

**Comment by nibblebits** [comment]
I reworded the argument to try to get a different outcome just to test if ChatGPT got it wrong

In UK if someone creates a software library that uses a private API that they were not allowed to integrate into software based on the Terms of service that the person signed. Are they personally liable for any damages caused by someone using their library. Can they be sued by the person who owns the private API and made those rules

A.I Response
If someone creates a software library that uses a private API in violation of the terms of service that the person signed, they could potentially be held liable for any damages caused by someone using their library. They could also be sued by the person or company that owns the private API for breach of contract. However, it ultimately depends on the specific terms of the contract and the circumstances of the case. It is always best to seek legal advice if you are unsure about your rights and obligations in such situations.


Okay I hope that clears it up, its your decision to keep the repository here. Though if your in China your probably fine hahaha

**Comment by bokesyo** [comment]
You are brainwashed by authoritarianism @ghost
