### ISSUE TITLE
Official vs Unofficial API

### ISSUE THREAD

**Issue by SpaceBurn** [acheong08/ChatGPT#504]
Hello, sorry if this is already answered somewhere, if it is I'm currently too tired to find it. What is the difference between the official and unofficial API and what are the pros and cons of both?

**Comment by acheong08** [comment]
The way I named it is kinda weird lol.

The "unofficial" API is the one used in `chat.openai.com` which makes it somewhat official as well. The issue is that it was reverse engineered from the website and against TOS. OpenAI has been making a ton of efforts to stop this and thus the requirement for browser.

The "official" API was found through a data leak in chat.openai.com and points to a model available from the standard completions endpoint. This means no browser. However, it also means memory and conversations must be handled by the library/user

**Comment by SpaceBurn** [comment]
> The way I named it is kinda weird lol.
> 
> The "unofficial" API is the one used in `chat.openai.com` which makes it somewhat official as well. The issue is that it was reverse engineered from the website and against TOS. OpenAI has been making a ton of efforts to stop this and thus the requirement for browser.
> 
> The "official" API was found through a data leak in chat.openai.com and points to a model available from the standard completions endpoint. This means no browser. However, it also means memory and conversations must be handled by the library/user

Thanks, out of interest do you think OpenAI intends to patch the "official" API or not?

**Comment by acheong08** [comment]
I think they will release it publicly and make it paid. I'm quite sure the fact that it's completely free on accounts without credit is a bug

**Comment by acheong08** [comment]
It charges money normally when the account has credit or is attached to a payment method

**Comment by LuckyHead11** [comment]
It's probably going to be included with ChatGPT Plus [https://openai.com/blog/chatgpt-plus/])

**Comment by Maxlinn** [comment]
after carefully reading upper replies, i draw following conclusions, if anyone knows better please correct me.

for real-or-fake:
1: the "official" version is implemented as an imitation of a leak, which demostrates the calling logics of actual chatgpt. so it can be concluded as actual chatgpt.
2: the "unofficial" version is definitely actual chatgpt because it just automated the openai chatgpt website window.

for restrictions:
3: the "official" version is paid only because it calls openai's charging davinci model. but if you have enough balance, it has no other restrictions. 
4: the "unofficial" version is free of charge but has the same restrctions as the openai chatgpt website, i.e. hourly calling limitations, slower responding speed, etc.

**Comment by acheong08** [comment]
> 3: the "official" version is paid only because it calls openai's charging davinci model. but if you have enough balance, it has no other restrictions.

Nope. There is a bug where if you use the API key of an account with $0 in credit, it works for free.

**Comment by Maxlinn** [comment]
> > 3: the "official" version is paid only because it calls openai's charging davinci model. but if you have enough balance, it has no other restrictions.
> 
> Nope. There is a bug where if you use the API key of an account with $0 in credit, it works for free.

that's much glad to hear!! but finally it will get patched someday(not now, hope for long)
